config/routes.rb
OneSixtyOne::Application.routes.draw do
 
 root to: "static_pages#home"
   

  resources :schools, only: [:new, :create, :index]

  resources :schools, only: [:show] do
    resources :users, only: [:index, :new, :create]
  end

  resources :schools, only: [:show] do
    resources :items, only: :index
  end 

  resources :users, only: [:show, :edit, :update, :delete] do
    member do
        get :following, :followers, :personal_item, :feed
      end
      resources :wants, only: :show
  end
  
  
  resources :items, only: [:create, :new, :edit, :show, :update, :delete] do
    resources :reactions, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :items, only: [:show] do
    resources :wants, only: [:create] do
    end
  end

resources :items, only: [:show] do
    resources :votes, only: [:create] do
    end
end

  resources :wants, only: [:update, :destroy] do
      resources :personals, only: [:create]
  end

  
  resources :sessions, only: [:new, :create, :destroy]

  match '/about',  to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  	if signed_in?
  	  @school = School.find(current_user.school_id)
  	  render 'home'
    else
  	  render 'home'
  end
end

  def about
  	if signed_in?
  	  @school = School.find(current_user.school_id)
  	  render 'about'
  
    else
    	render 'about'
  end
end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>


<div class="center hero-unit">
  <h1>About the 161 App</h1>
    <p> The project I am working on right now is a web app that allows students at a college to crowd source a list of things to do before you graduate.  At Cornell we had a list that one person was able to decide on, but I am imagining an app that lets people "like" a certian task moving it higher in the rankings.  That way everyone gets a say.  Each student will be able to have a profile page that allows them to make a list of the tasks they have completed with a picture or video attached.  You will be able to search for friends and add them to you list of favorites.  To keep the app in check students can submit suggestions but their real email address will be attached to it.  I think it will be great, check back when I have a working model.  Thanks! </p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
  <h1>Welcome to the 161 App.  You finally have a say in the matter.</h1>
 </div>
      <% unless signed_in? %>
      <div class='row'>
      	<div class='span4 offset8'>
          <%= link_to "Sign me up!", new_school_path, class: "btn btn-large btn-primary" %>
        </div>
      <div class='span4 offset8'></br>
      
        <%= link_to "Log me in!", signin_path, class: "btn btn-primary btn-large" %>
      </div>
      <% end %>
  </div>
    