config/routes.rb
OneSixtyOne::Application.routes.draw do
 
 root to: "static_pages#home"
   

  resources :schools, only: [:new, :create, :index]

  resources :schools, only: [:show] do
    resources :users, only: [:index, :new, :create]
  end

  resources :schools, only: [:show] do
    resources :items, only: :index
  end 

  resources :users, only: [:show, :edit, :update, :delete] do
    member do
        get :following, :followers, :personal_item, :feed
      end
      resources :wants, only: :show
  end
  
  
  resources :items, only: [:create, :new, :edit, :show, :update, :delete] do
    resources :reactions, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :items, only: [:show] do
    resources :wants, only: [:create] do
    end
  end

resources :items, only: [:show] do
    resources :votes, only: [:create] do
    end
end

  resources :wants, only: [:update, :destroy] do
      resources :personals, only: [:create]
  end

  
  resources :sessions, only: [:new, :create, :destroy]

  match '/about',  to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  email                :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  password_digest      :string(255)
#  remember_token       :string(255)
#  school_id            :integer
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :picture
  has_secure_password

  has_many :items
  has_many :reactions, dependent: :destroy
  has_many :wants, dependent: :destroy
  has_many :personal_items, through: :wants, source: :item
  has_many :votes, dependent: :destroy
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_attached_file :picture, styles: { small: "300x300", tile: "50x50", icon: "100x100" }, default_url: '/images/:style/missing.png'

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGREX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGREX },
                                    uniqueness: { case_sensative: false }
   validates :password, presence: true, length: { minimum: 6 }
   validates :password_confirmation, presence: true
   #validates :picture, size: { in: 0..30.kilobytes }



  def feed
    Want.from_users_followed_by(self)
  end

  def add_item(item)
    self.wants.create(item_id: item.id)
  end

  def add_vote(item)
    self.votes.create(item_id: item.id)
  end

  def following?(other_user)
    self.relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    self.relationships.create(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    self.relationships.find_by_followed_id(other_user.id).destroy
  end

   private

   def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
   end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :signed_in_user, only: [:index, :show, :edit, :update, :destroy, :following, :followers, :personal_item]
  def new
  	@school = School.find(params[:school_id])
  	@user = User.new
  end

  def index
  	@school = School.find(current_user.school_id)
    if params[:search]
      @users = @school.users.find(:all, conditions: ["name like ?", "%#{params[:search]}%"])
    else
  	  @users = @school.users.paginate(page: params[:page])
    end
  end

  def show
  	@user = User.find(params[:id])
    @school = School.find(current_user.school_id)
    @wants = @user.wants
  end

  def create
  	@school = School.find(params[:school_id])
  	@user = @school.users.build(params[:user])
  	if @user.save
  	  sign_in @user
  	  flash[:success] = 'Welcome to the app!'
  	  redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(params[:user])
  		flash[:success] = "Successful Update"
      sign_in @user
  		redirect_to user_path(@user)
  	else
      flash[:error] = "That didn't work, try again please."
  		render 'edit'
  end
end

  def destroy
  	User.find(params[:id]).destroy
  	flash[:succes] = "User destroyed!"
  	render 'index'
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    @school = School.find(current_user.school_id)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    @school = School.find(current_user.school_id)
    render 'show_follow'
  end

  def personal_item
    @title = "My Items"
    @user = User.find(params[:id])
    @school = School.find(current_user.school_id)
    @want = Want.find(params[:format])
    @personal_item = Item.find(@want.item_id)
    @personal = Personal.new
    
  end

  def feed 
    @user = User.find(params[:id])
    @users = @user.followed_users
    @wants = @users.collect { |user| user.wants }
    @votes = @users.collect { |user| user.votes }
    @combo = [@wants, @votes].flatten
    @combo_ordered = @combo.sort_by(&:updated_at).reverse
  end

end

app/helpers/users_helper.rb
module UsersHelper


	def gravatar_for(user) 
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_did_it.html.erb
<%= form_for(item) do |f| %>

<%= f.hidden_field :status %>
<%= f.submit "I did it", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>

<%= f.hidden_field :followed_id %>
<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user == current_user %>

  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>

  <% else %>

  <%= render 'follow' %>

  <% end %>
  <% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user.id), html: { method: :delete }) do |f| %>

<%= f.submit "Unfollow", class: "btn btn-large" %>

<% end %>

app/views/users/_user.html.erb
<% provide(:title, "All users") %>



<ul class="users">


	<% @users.each do |user| %>

	<li>
		
		<%= link_to user.name, user_path(user) %>
		
	</li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Your Profile') %>

<div class="center hero-unit">
    <h1>Edit Your Profile</h1>
    
</div>

<%= render 'shared/flashes' %>

<div class="row">
	<div class="span6 offset6">
		<%= form_for @user do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

		  <%= f.label :name %>
		  <%= f.text_field :name %>

		  <%= f.label :email %>
		  <%= f.text_field :email %>

		  <%= f.label :password %>
		  <%= f.text_field :password %>

		  <%= f.label :password_confirmation, "Confirmation" %>
		  <%= f.text_field :password_confirmation %></br>

		  <%= f.file_field :picture %>

		  <div class="container"></br>

		 <%= f.submit "Update My Profile!",  class: "btn btn-large btn-primary" %>
		  </div>
		 <% end %>
	</div>
</div>

app/views/users/feed.html.erb
<div class="center hero-unit">
    <h1>Recent Activity</h1>
</div>

    <div class="center hero-unit">
  

  <ul><% @combo_ordered.each do |recent_item| %>

  	
    <% if recent_item.class == Vote %>
       <% user = User.find(recent_item.user_id) %>
        <%= image_tag user.picture.url(:icon) %>
  	   <%= link_to "#{user.name} +1'd this item >>", user_path(user)  %>
  	   <% item = Item.find(recent_item.item_id) %>
  	   <%= link_to "#{item.content}", item_path(item) %>
       <%= "Updated #{time_ago_in_words(recent_item.updated_at)} ago" %></br>
    <% else %>
  	  <% user = User.find(recent_item.user_id) %>
  	  <% if recent_item.created_at == recent_item.updated_at %>
         <%= image_tag user.picture.url(:icon) %>
  	     <%= link_to "#{user.name} added to personal list >>", user_path(user)  %>
  	     <% item = Item.find(recent_item.item_id) %>
  	     <% want = user.wants.find_by_item_id(item) %>
  	     <%= link_to "#{item.content}", item_path(item) %>
         <%= "Updated #{time_ago_in_words(recent_item.updated_at)} ago" %></br>
      <% else %>
        <%= image_tag user.picture.url(:icon) %>
  	    <%= link_to "#{user.name} updated >> ", user_path(user)  %>
  	    <% item = Item.find(recent_item.item_id) %>
  	     <% want = user.wants.find_by_item_id(item) %>
  	     <%= link_to "#{item.content}", personal_item_user_path(user, want) %>
         <%= "Updated #{time_ago_in_words(recent_item.updated_at)} ago" %></br>
  	  <% end %>
     
  <% end %>
  <% end %>
 </ul>

</div>

app/views/users/index.html.erb
<div class="center hero-unit">
  <h1><%=@school.name%></h1>
    
</div>

<%= form_tag school_users_path(@school), method: :get do %>

<p>
	<%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
 </p>
 <% end %>


<div class="center hero-unit">
<% @users.each do |user| %>

<h1><%= link_to user.name, user_path(user) %></h1>

<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="center hero-unit">
    <h1>Step 2.</h1>
  <h1>Give us just enough info to log you in.  No more, we promise.</h1>
    
</div>

<%= render 'shared/flashes' %>

<div class="row">
	<div class="span6 offset6">
		<%= form_for [:school, @user] do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

		  <%= f.label :name %>
		  <%= f.text_field :name %>

		  <%= f.label :email %>
		  <%= f.text_field :email %>

		  <%= f.label :password %>
		  <%= f.text_field :password %>

		  <%= f.label :password_confirmation, "Confirmation" %>
		  <%= f.text_field :password_confirmation %></br>

		  <%= f.file_field :picture %>

		  <div class="container"></br>

		 <%= f.submit "Create my account!",  class: "btn btn-large btn-primary" %>
		  </div>
		 <% end %>
	</div>
</div>

app/views/users/personal_item.html.erb
<div class="center hero-unit">
<%= @personal_item.content %>

</div>


<div class="center hero-unit">

<%= image_tag(@want.picture.url) %>


<% @want.personals.each do |personal_comment| %>

<% the_user = User.find(personal_comment.user_id) %>
<%= the_user.email %>
<%= personal_comment.content %></br>

<% end %>

</div>

<% if current_user == @user %>

<div class="span8 offset4">
		<%= form_for @want, html: { multipart: true } do |f| %>
		<%= render 'shared/error_messages', object: f.object %>


        <% if @want.picture.blank? %>

		  <%= f.file_field :picture %>

		  <%= f.check_box(:status) %>
          <%= f.label :status, "I did it!" %>

        <% else %>

          <%= f.check_box(:status) %>
          <%= f.label :status, "I did it!" %>
        <% end %>


		<%= f.submit "Submit!", class: 'btn btn-large btn-primary' %>

		<% end %>
	</div>
</div>

<% end %>

<div class="span8 offset4">
		<%= form_for [@want, @want.personals.build(user_id: current_user.id)] do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :content %>
		<%= f.text_field :content %>

		<%= f.hidden_field :user_id %>

		<%= f.submit "Add your comment!", class: 'btn btn-large btn-primary' %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
  	<%= render 'shared/flashes' %>
    <section>
      <h1>
        <%= image_tag @user.picture.url(:icon) %>
        <%= @user.name %>
        <% if current_user == @user %>
        <%= link_to "Edit My Profile", edit_user_path(@user) %>
        <% end %>
        <%= render 'follow_form' %>
      </h1>
    </section>
    <section>
    	<%= render 'shared/stats' %>
    </section>
  </aside>
</div>


  <div class="center hero-unit">
  <% @wants.each do |item| %>
    <p><% my_wants = Item.find(item.item_id) %><p>
     <p><%= link_to "#{my_wants.content}", personal_item_user_path(@user, item) %><p>
      <% unless @user != current_user %>
     <p><%= link_to image_tag("glyphicons_192_circle_remove.png"), want_path(item), method: :delete %><p>
      <% end %>
     <% if item.status == 0 %>
        
        <p><%= image_tag("glyphicons_153_unchecked.png") %> </p>
       <% else %>
       <p><%= image_tag("glyphicons_152_check.png") %> </p>
       <% end %>

  <% end %>
</div>

<p>Find me in app/views/users/show.html.erb</p>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", user_path(@user) %></span>
      <span><b>Things they like:</b> <%= @user.wants.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
           
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |user| %>

        
      </ul>
      
    <% end %>
  </div>
</div>