config/routes.rb
OneSixtyOne::Application.routes.draw do
 
 root to: "static_pages#home"
   

  resources :schools, only: [:new, :create, :index]

  resources :schools, only: [:show] do
    resources :users, only: [:index, :new, :create]
  end

  resources :schools, only: [:show] do
    resources :items, only: :index
  end 

  resources :users, only: [:show, :edit, :update, :delete] do
    member do
        get :following, :followers, :personal_item, :feed
      end
      resources :wants, only: :show
  end
  
  
  resources :items, only: [:create, :new, :edit, :show, :update, :delete] do
    resources :reactions, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :items, only: [:show] do
    resources :wants, only: [:create] do
    end
  end

resources :items, only: [:show] do
    resources :votes, only: [:create] do
    end
end

  resources :wants, only: [:update, :destroy] do
      resources :personals, only: [:create]
  end

  
  resources :sessions, only: [:new, :create, :destroy]

  match '/about',  to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer>
   	
   	<div class="copyright"><p>&copy; Jake Dean, 161 App 2013</p></div>
    
    <div class="crafted">
    	<p>Crafted with Ruby on Rails</p>
    	<div id="rails_pic">
    	<%= link_to image_tag("rails.png", size: "45x45", alt: "Rails"), 'https://rubyonrails.org' %>
    	</div
  </footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "161", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
                <%if signed_in? %>
                  <li><%= link_to "My School List", school_items_path(current_user.school_id) %></li>
                  <li><%= link_to "Users", school_users_path(current_user.school_id) %></li>
                  <li><%= link_to "My Profile", user_path(current_user)%></li>
                  <li><%= link_to "Recent Activity", feed_user_path(current_user) %></li>
                  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                <% else %>
                  <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="flashes">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>